- src/engine-driver/proxy/remote_driver.cr
useful for executing commands from within the cluster
> feat: add remote module helper

- shard.yml
- src/driver/driver-specs/runner.cr
- src/driver/protocol.cr
- src/driver/protocol/management.cr
- src/driver/transport/ssh.cr
- src/driver/transport/tcp.cr
- src/driver/transport/udp.cr
- src/driver/transport/websocket.cr
- src/driver/utilities/wake_on_lan.cr
note warnings will be removed seperately
> feat: add crystal 0.34 compatibility

- shard.yml
- src/driver/constants.cr
- src/driver/logger.cr
- src/driver/logger_io.cr
- src/driver/subscriptions.cr
File separation prevents resolution of Driver's internal logger
> fix(logger): create `constants.cr` and `logger_io.cr`

- src/driver/driver-specs/mock_driver.cr
- src/driver/driver_manager.cr
- src/driver/process_manager.cr
- src/driver/protocol.cr
- src/driver/protocol/management.cr
- src/driver/proxy/driver.cr
- src/driver/proxy/scheduler.cr
- src/driver/proxy/system.cr
- src/driver/subscriptions.cr
- src/driver/subscriptions/channel_subscription.cr
- src/driver/subscriptions/direct_subscription.cr
- src/driver/subscriptions/indirect_subscription.cr
- src/driver/task.cr
- src/driver/transport.cr
- src/driver/transport/ssh.cr
- src/driver/transport/tcp.cr
- src/driver/transport/udp.cr
- src/driver/transport/websocket.cr
improves ssh authentication and logging performance
fixes #9
> feat: update logger and ssh2 shards

- shard.yml
- src/driver/transport/ssh.cr
Also handles authentication errors in case multiple auth options were provided
> feat: add support for keyboard-interactive auth

- src/driver/queue.cr
> fix(queue): online state not set on initial disconnect

- src/placeos-driver/transport/tcp.cr
> fix(transport/tcp): close local socket on remote disconnect

- docs/system_operation.md
- shard.yml
- spec/driver_proxy_spec.cr
- spec/drivers_proxy_spec.cr
- spec/logger_spec.cr
- spec/subscription_proxy_spec.cr
- spec/subscription_spec.cr
- src/driver
- src/placeos-driver/driver-specs/mock_driver.cr
- src/placeos-driver/driver-specs/runner.cr
- src/placeos-driver/protocol/management.cr
- src/placeos-driver/proxy/system.cr
- src/placeos-driver/storage.cr
- src/placeos-driver/subscriptions.cr
- Strips pooled redis clients
- Clients default to a standard redis client when the redis server is a single node
> feat: HA Redis

- shard.yml
- spec/protocol_management_spec.cr
- src/placeos-driver/protocol/management.cr
Factor in some explicit getters and set type of `pid` ivar to `Int64`
> refactor(management): explicit typing

- src/placeos-driver/transport/ssh.cr
- src/placeos-driver/transport/tcp.cr
- src/placeos-driver/transport/udp.cr
- src/placeos-driver/transport/websocket.cr
which otherwise might prevent re-connection
fixes #30
> fix(transports): ensure IO is marked as closed

- src/placeos-driver/proxy/system.cr
improves readability
fixes PlaceOS/drivers#22
> feat(proxy system): overload system subscribe

- shard.yml
- src/placeos-driver.cr
> fix(driver): support drivers with no public methods

- shard.yml
- src/placeos-driver/interface/email.cr
Simple interface for drivers that send emails
> feat(interface): add email interface

- shard.yml
- src/placeos-driver/proxy/remote_driver.cr
- src/placeos-driver/proxy/system.cr
> improvement(proxy): type `get_parts`

- shard.yml
- spec/transport_ssh_spec.cr
- src/placeos-driver.cr
- src/placeos-driver/protocol/management.cr
- src/placeos-driver/proxy/system.cr
fixes #52
@caspiano this adds a new callback that should be implemented in core to obtain the system model
should be a simple addition
> feat: add support for accessing remote systems

- src/placeos-driver/driver_manager.cr
- src/placeos-driver/transport/websocket.cr
> feat(websocket transport): allow for dynamically defined headers

- shard.yml
- src/placeos-driver/driver-specs/mock_driver.cr
Should resolve an issue where `::PlaceOS::Driver::Task` was not resolving
> fix(mock_driver): require and resolve Task symbol

- shard.yml
- src/placeos-driver/driver-specs/mock_driver.cr
Magic related to horrendous class/module resolution
> fix(mock_driver): reorder requires

- src/placeos-driver/exception.cr
- src/placeos-driver/proxy/driver.cr
to be able to locate where the request came from
> fix(driver proxy): exceptions don't have enough information

- src/placeos-driver/transport/http.cr
> fix(http transport): errors not displaying as offline in backoffice

- .github/workflows/ci.yml
- spec/scheduler_spec.cr
- src/placeos-driver.cr
- src/placeos-driver/proxy/scheduler.cr
> style: address feedback of #70

- src/placeos-driver/transport.cr
for use with websocket drivers
> fix(base transport): improve default HTTP client

- shard.yml
- spec/helper.cr
- src/placeos-driver.cr
- src/placeos-driver/utilities/discovery.cr
so it is stored in redis allowing logic modules to discover what sources are available on switchable interfaces for example
this also exposes json schema at driver creation time for use by the frontend / saving in the driver model
> feat: JSON schema should be included in driver metadata

- shard.yml
- spec/scheduler_spec.cr
- spec/transport_http_spec.cr
- src/placeos-driver.cr
- src/placeos-driver/driver_manager.cr
- src/placeos-driver/transport.cr
- src/placeos-driver/transport/http.cr
maintains backwards compatibility
> feat(http transport): add before_request and use URI::Params

- shard.yml
- src/placeos-driver.cr
we don't want warnings being emited when trying to output metadata
> feat: improve driver processing of startup options

- src/placeos-driver.cr
> fix: support drivers with no methods

- shard.yml
- src/placeos-driver/transport/http.cr
better adherence to the HTTP 1.1 requirements
> feat(transport http): improve http client keep alive

- shard.yml
- spec/transport_http_spec.cr
- src/placeos-driver/driver_manager.cr
- src/placeos-driver/transport.cr
- src/placeos-driver/transport/http.cr
also allow bodies on delete requests.
This resolves the remaining issues flagged in the Lenel driver
> feat(transport http): refactor before_request implementation

- shard.yml
- src/placeos-driver.cr
- src/placeos-driver/driver-specs/mock_driver.cr
- src/placeos-driver/spec.cr
- src/placeos-driver/storage/redis-storage.cr
also clean up generated drivers docs
> feat: add a shortcut for requiring driver specs

- spec/drivers_proxy_spec.cr
- src/placeos-driver.cr
- src/placeos-driver/driver-specs/mock_driver.cr
- src/placeos-driver/proxy/driver.cr
also fixes mock driver where it wasn't generating the new function interface
resolves PlaceOS/drivers#193
> fix(driver proxy): handle default params with new function interface

- .github/workflows/ci.yml
- shard.yml
- src/placeos-driver/proxy/remote_driver.cr
> refactor: use core client

- src/placeos-driver/driver_model.cr
- src/placeos-driver/proxy/driver.cr
for use with the room bookings driver as a default
> feat(driver model): add support url to model

- shard.yml
- src/placeos-driver/proxy/remote_driver.cr
> fix: use core client shard

- .github/workflows/ci.yml
- shard.yml
- spec/driver_proxy_spec.cr
- spec/helper.cr
- spec/process_manager_spec.cr
- spec/protocol_management_spec.cr
- spec/protocol_spec.cr
- spec/queue_spec.cr
- src/placeos-driver.cr
- src/placeos-driver/driver-specs/runner.cr
- src/placeos-driver/driver_manager.cr
- src/placeos-driver/interface/camera.cr
- src/placeos-driver/interface/powerable.cr
- src/placeos-driver/logger.cr
- src/placeos-driver/process_manager.cr
- src/placeos-driver/protocol.cr
- src/placeos-driver/protocol/management.cr
- src/placeos-driver/protocol/request.cr
- src/placeos-driver/proxy/driver.cr
- src/placeos-driver/proxy/system.cr
- src/placeos-driver/storage.cr
- src/placeos-driver/storage/edge-storage.cr
- src/placeos-driver/storage/redis-storage.cr
- src/placeos-driver/subscriptions.cr
- src/placeos-driver/task.cr
- src/placeos-driver/transport.cr
- src/placeos-driver/transport/websocket.cr
- src/placeos-driver/utilities/discovery.cr
- src/placeos-driver/utilities/wake_on_lan.cr
General refactor of a few things across the library.
It's best to review this per commit instead of the whole set of changes.
> refactor: getters, enums, case statements etc

- shard.yml
- src/placeos-driver/proxy/remote_driver.cr
Propagates request_id on debug requests
> fix(proxy:remote_driver): request_id not in scope

- shard.yml
- src/placeos-driver/interface/sensor.cr
and remove unit conversions (as this is not currently used)
> feat(interface sensor): add air quality measurement

- shard.yml
- spec/storage_spec.cr
- src/placeos-driver/driver_manager.cr
- src/placeos-driver/status.cr
- src/placeos-driver/storage/edge-storage.cr
- src/placeos-driver/storage/redis-storage.cr
- src/placeos-driver/transport.cr
- src/placeos-driver/transport/websocket.cr
helps with debugging connectivity issues in drivers
> feat(driver transport): provide status level feedback on proxy usage

- shard.yml
- src/placeos-driver/transport.cr
- src/placeos-driver/transport/websocket.cr
when initialising proxied version of HTTP classes
> fix(transport proxy): only apply explicitly set proxies

- shard.yml
- spec/drivers_proxy_spec.cr
- src/placeos-driver/driver_model.cr
- src/placeos-driver/proxy/driver.cr
> feat(driver proxy): __send__ not to use splats

- shard.yml
- src/placeos-driver/driver-specs/runner.cr
prevents errors when on_unload runs
also fixes on_update being called when the system module config is updated
> fix(driver spec runner): stop module before termination

- src/placeos-driver/process_manager.cr
- src/placeos-driver/protocol.cr
- src/placeos-driver/protocol/management.cr
- src/placeos-driver/proxy/scheduler.cr
- src/placeos-driver/proxy/system.cr
- src/placeos-driver/queue.cr
- src/placeos-driver/subscriptions.cr
This gives more control over logging specific to PlaceOS.
> refactor(logging): ensure logs scoped under `place_os`

- src/placeos-driver/proxy/remote_driver.cr
where module names have underscores
> fix(proxy remote driver): improve module name parsing

- src/placeos-driver/driver_manager.cr
as these lifecycle events could block other aspects of the system if they don't return in a timely manaer
> feat(driver manager): add timeouts for load and unload

- shard.yml
- src/placeos-driver/transport/ssh.cr
however it is an optional part of SSH so might not be required, however we should re-connect if it is required
> fix(transport ssh): as shell negotiation might fail

- shard.yml
- src/placeos-driver/transport/ssh.cr
we ensure that @messages channel can be used to trigger a reconnect when running in shell mode
> fix(transport ssh): no shell would never disconnect

- .github/workflows/ci.yml
- src/placeos-driver/driver_manager.cr
- src/placeos-driver/process_manager.cr
- src/placeos-driver/protocol/management.cr
> refactor(protocol/management): exhaustive case on driver type

- shard.yml
- spec/transport_http_spec.cr
- src/placeos-driver/subscriptions.cr
- src/placeos-driver/transport.cr
- src/placeos-driver/transport/http.cr
> feat(transport http): add support for transparent HTTP Cookies

- shard.yml
- src/placeos-driver/driver-specs/runner.cr
allows specs to emit events for drivers to pick up
> feat(driver-specs/runner): add support for testing monitored events

- .github/workflows/ci.yml
- shard.override.yml
- shard.yml
- src/placeos-driver.cr
as this shells out instead of running the process directly
> fix: don't use back ticks to obtain interface

- shard.yml
- src/placeos-driver.cr
- src/placeos-driver/queue.cr
so drivers don't need to implement the logic
> feat: add termination check helper

- shard.yml
- src/placeos-driver/interface/chat_bot.cr
Adds a chat bot interface for Cisco Webex and such, for now we can use a minimal class
> Add Chat Bot interface

- shard.yml
- src/placeos-driver/transport/udp.cr
> fix(transport/udp): connect doesn't work for multicast data

- shard.yml
- src/driver.cr
- src/placeos-driver.cr
- src/placeos-driver/driver_model.cr
- src/placeos-driver/proxy/remote_driver.cr
- src/placeos-driver/proxy/system.cr
also fix use of deprecated method
> feat: update metadata for LLM usage

- shard.yml
- src/placeos-driver/protocol/management.cr
- src/placeos-driver/transport/ssh.cr
- src/placeos-driver/transport/tcp.cr
- src/placeos-driver/transport/udp.cr
this ensures they terminate asap
> fix: modules failing to connect may not stop

- .github/workflows/ci.yml
- shard.yml
- src/placeos-driver/protocol/management.cr
ensure this critical path is successful
> fix(protocol/management): ensure driver load success

- shard.yml
- src/placeos-driver/driver_manager.cr
- src/placeos-driver/process_manager.cr
- src/placeos-driver/queue.cr
frees up a fiber per module instance
> feat: reduce spawn usage
