src/driver/proxy/driver.cr
src/driver/proxy/drivers.cr
src/driver/utilities/discovery.cr

Ensure that issues detected during macro expansion raise appropriate
compile-time errors.

fix: raise compile-time errors from macros

---

shard.yml
spec/driver_proxy_spec.cr
spec/drivers_proxy_spec.cr
spec/helper.cr
spec/logger_spec.cr
spec/process_manager_spec.cr
spec/protocol_spec.cr
src/driver.cr
src/driver/driver-specs/mock_driver.cr
src/driver/driver-specs/runner.cr
src/driver/logger.cr
src/driver/protocol.cr
src/driver/protocol/management.cr
src/driver/subscriptions.cr
src/driver/transport/http.cr
src/driver/transport/ssh.cr
src/driver/transport/tcp.cr
src/driver/transport/udp.cr
src/driver/transport/websocket.cr

As STDERR might be used for error output the STDERR protocol needs to be encapsulated to allow for this.
retriable.cr erroring both made me aware of this and the fact that it wasn't working.

fix driver protocol and remove retriable.cr

---

shard.yml
src/placeos-driver.cr

Explicit build error when a public driver method is missing a type.
Example:
```
Code in drivers/place/feature_test.cr:3:1
3 | class Place::AcidTest < PlaceOS::Driver
^
Called macro defined in lib/placeos-driver/src/placeos-driver.cr:166:3
166 | macro inherited
Which expanded to:
> 1 | macro finished
^
Error: Place::AcidTest#perform_thing argument `name` is missing a type
```
Resolves #24

improvement: helpful errors when missing type restriction in a driver method

---

src/placeos-driver/utilities/transcoder.cr

I wanted to do `def array_to_bytes(array : Array(Int))` instead of `def array_to_bytes(array : Array(UInt8))` so it doesn't matter what type of Int the Array has but the driver rest runner gives this error.

fix(transcoder): add types to params

---

spec/driver_proxy_spec.cr
src/placeos-driver/proxy/driver.cr
src/placeos-driver/proxy/drivers.cr

the caller sets the default arguments not the receiver

fix(proxy driver): set default arguments on execute

---

shard.yml
src/placeos-driver/proxy/driver.cr
src/placeos-driver/proxy/remote_driver.cr

- `ErrorCode` enum was not utilising the `Flags` annotation
- extract exec payload generation into a class method to fix a complexity lint and make it easier to generate test exec payloads

refactor: enum flags

---

spec/subscription_proxy_spec.cr
src/placeos-driver.cr
src/placeos-driver/proxy/system.cr
src/placeos-driver/storage/redis-storage.cr

to reduce the number of connections made by each driver.
previously a new connection for every module instance - which has lead to hitting redis connection limits

feat(redis-storage): use a shared redis client

---

shard.yml
spec/protocol_management_spec.cr
src/placeos-driver/protocol/management.cr

* Adds a method `PlaceOS::Driver::Protocol::Management#ignore_all(module_id : String) : Array(String -> Nil)` to remove all debug listeners on a module, returning the debug callbacks that were present.
* Prevents an exception raised in a debug callback from preventing forwarding debug messages to remaining callbacks
* Fixes a handful of ameba lints

feat: bulk `ignore`

---

shard.yml
src/placeos-driver.cr
src/placeos-driver/driver-specs/mock_driver.cr
src/placeos-driver/exception.cr
src/placeos-driver/process_manager.cr
src/placeos-driver/proxy/system.cr
src/placeos-driver/subscriptions.cr
src/placeos-driver/transport/http.cr
src/placeos-driver/utilities/wake_on_lan.cr

`Log` was being configured at the instance level, at multiple sites.
Includes the cleanup of a handful of lints.

fix: redundant log configuration

---

.travis.yml
shard.yml
src/placeos-driver/driver_model.cr
src/placeos-driver/logger.cr
src/placeos-driver/transport.cr
src/placeos-driver/transport/http.cr

I assume this occurs when the body has not been completely sent when parsing the response. This ensures consistency when drivers are communicating over HTTP

fix: sometimes the HTTP client lib does't decompress the response

---

shard.yml
src/placeos-driver/protocol/management.cr

Fixes a deadlock error when bulk ignoring debug callbacks on a running driver's protocol manager.

fix(protocol/management): reentrant debug lock

---

shard.yml
src/placeos-driver/status.cr
src/placeos-driver/storage.cr
src/placeos-driver/storage/edge-storage.cr
src/placeos-driver/storage/redis-storage.cr
src/placeos-driver/utilities/discovery.cr

Extending stdlib interfaces is generally frowned upon by the crystal community. 
In this case, this PR is a step towards unblocking sentry integration. 
Includes a small optimisation to `RedisStorage#to_h`
See PlaceOS/rest-api/pull/89 and the referenced Raven.cr issue

refactor(storage): stop extending stdlib hash

---

shard.yml
src/placeos-driver/interface/electrical_relay.cr

Adds a missing type `intial_state` argument of `PlaceOS::Driver::Interface::ElectricalRelay#pulse`

fix(interface/electrical_relay): add missing type to #pulse

---

spec/settings_spec.cr
spec/test_build.cr
src/placeos-driver.cr
src/placeos-driver/driver_model.cr
src/placeos-driver/settings.cr
src/placeos-driver/settings/introspect.cr
src/placeos-driver/transport/ssh.cr
src/placeos-driver/utilities/discovery.cr

generates this based on the extraction of settings fixes PlaceOS/rest-api#114
Existing limitations:
* settings can technically extract sub keys `setting(String, :base, :subkey)` and these are ignored due to complexity
I don't think any driver is using sub keys at this time

feat: add json schema to driver metadata

---

.github/workflows/ci.yml
shard.yml
spec/driver_proxy_spec.cr
spec/driver_spec.cr
spec/drivers_proxy_spec.cr
spec/scheduler_spec.cr
spec/settings_spec.cr
src/placeos-driver.cr
src/placeos-driver/driver_model.cr
src/placeos-driver/proxy/driver.cr
src/placeos-driver/proxy/scheduler.cr
src/placeos-driver/proxy/system.cr
src/placeos-driver/settings/introspect.cr

previously it exposed the type name, purely for metadata, but this is much more useful and could be used in backoffice when executing functions to ensure you're entering valid values
no breaking changes by json encoding the schema as a string
This means when you have an argument that is a JSON serialisable object like
```crystal
class Testing
include JSON::Serializable
property email : String
property mobile : String?
end
```
then you get something meaningful in the metadata instead of just `Testing`

feat(metadata): use json schema for function arguments

---

shard.yml
src/placeos-driver.cr
src/placeos-driver/driver-specs/mock_driver.cr
src/placeos-driver/proxy/system.cr
src/placeos-driver/queue.cr
src/placeos-driver/task.cr
src/placeos-driver/utilities/discovery.cr

replaces the array over an in-place update
```crystal
@queue.sort! { |a, b| a.apparent_priority <=> b.apparent_priority }
@queue.reject! { |t| t != task && t.name == name }
```
and
```crystal
@queue = @queue.sort { |a, b| a.apparent_priority <=> b.apparent_priority }
@queue = @queue.reject { |t| t != task && t.name == name }
```

fix(queue): replace priority queue

---

shard.yml
src/placeos-driver/transport.cr
src/placeos-driver/transport/http.cr

also removes redundant calls to `compress = true`

feat(transport http): add support for overriding the Host header

---

shard.yml
src/placeos-driver/proxy/scheduler.cr

A handful of drivers reference this private class, causing them to fail to compile. This PR makes the class public, fixing the compilation errors.

fix(proxy/scheduler): make `TaskWrapper` public

---

shard.yml
src/placeos-driver/proxy/drivers.cr

the failures are logged but one failed request of many shouldn't prevent the results being collected.
The main reason for this to occur is when a driver has been stopped and hence the request never makes it.
old behaviour is now optional

feat(proxy drivers): ignore failures occuring on batch results

---

src/placeos-driver.cr
src/placeos-driver/driver_manager.cr
src/placeos-driver/protocol.cr
src/placeos-driver/protocol/management.cr
src/placeos-driver/protocol/request.cr
src/placeos-driver/proxy/driver.cr
src/placeos-driver/proxy/remote_driver.cr

using Fiber names we can associate users with code execution at the driver level.
This is good for logging and useful in Logic modules where user identity might be important.

feat: add invoked_by_user_id as a security context in requests

---

shard.yml
src/placeos-driver.cr
src/placeos-driver/driver-specs/runner.cr

prevents false negatives due to race conditions in device driver specs

fix(driver specs runner): ensure transmission processing is synced

---

shard.yml
src/placeos-driver/driver-specs/runner.cr

otherwise a following transmission can overwrite the existing data that is still being processed

fix(driver specs runner): buffer data needs to be duplicated

---

shard.yml
src/placeos-driver/protocol/request.cr

only used by Edge for processing on core
@caspiano this might be a breaking change for Core, however I need the change for driver compiling
may have never noticed this except for your refactor, nice one

fix(protocol request): add missing publish command

---

shard.yml
src/placeos-driver/transport/ssh.cr

I assume this is due to a callback capturing a stack variable versus a heap variable as the issue occurred when interacting with the string.
Storing the state in an instance variable solved the issue

fix(ssh transport): segfault performing interactive logon

---

shard.yml
spec/protocol_management_spec.cr
src/placeos-driver/protocol/management.cr

Recent changes added support for a publish command.
This adds the handler for the new event.

fix(protocol): add missing redis PUBLISH proxy handler

---

.github/workflows/ci.yml
shard.yml
src/placeos-driver/storage/edge-storage.cr

`empty?` was not implemented on the `EdgeStorage` class

fix(edge-storage): implement `empty?` on EdgeStorage

---

src/placeos-driver/protocol/management.cr

When testing the hypothesis that driver's blocked on IO do not successfully restart, we noticed that an IO could remain open to the driver, potentially blocking the `relaunch` event from triggering a reload of the driver.

fix(protocol manager): ensure IO closed on driver exit

---

.github/workflows/ci.yml
shard.yml
src/placeos-driver/protocol/management.cr

This PR adds the `user_id` in `exec` requests.
Ideally, we would serialize the `Request` object directly to simplify changes to the data model.

fix(protocol): pass `user_id` in the hand-constructed exec request

---

shard.yml
spec/protocol_management_spec.cr
src/placeos-driver/driver_manager.cr
src/placeos-driver/exception.cr
src/placeos-driver/protocol/management.cr
src/placeos-driver/protocol/request.cr
src/placeos-driver/proxy/remote_driver.cr
src/placeos-driver/task.cr

I think it's worth having a discussion if this is actually worth implementing.
Like what are the advantages etc.
The driver level protocol is backwards compatible and we would have to:
* update the core API to return the code (in a header which would maintain backwards compatibility)
* update the core API Client to return the code
* update rest-api to return the code
in the scheme of things, not the biggest change

feat: add success and failure codes to request processing

---

shard.yml
spec/driver_spec.cr
spec/process_manager_spec.cr
spec/test_build.cr
src/placeos-driver.cr
src/placeos-driver/driver_manager.cr
src/placeos-driver/utilities/rescue_from.cr

There is an inline form
```crystal
rescue_from DivisionByZeroError do |error|
-1
end
```
and an explicit form
```crystal
rescue_from IndexError, :handle_index
protected def handle_index(error)
-2
end
```
These only handle errors that occur when executing a function
if the error occurs in the `received` function it must be handled there
fixes #140

feat: add `rescue_from` helper methods

---

shard.yml
src/placeos-driver/proxy/driver.cr
src/placeos-driver/proxy/remote_driver.cr

including providing access to the new response code internally in drivers

fix(proxy/remote_driver): propagate error responses properly

---

shard.yml
src/placeos-driver.cr

**Description of the change**
Fixes a bug where log output would break deserialisation of the output of the defaults emitted by a driver

fix(`-d`): prevent log leaking into defaults output

---

shard.yml
src/placeos-driver/driver-specs/runner.cr

can spec if the update had the expected in two ways:
```crystal
define_setting("key", {value: 1234})
@current_settings["key"]?.should eq {"value" => 1234}
```
OR
```crystal
define_setting("key", {value: 1234})
def on_update
self[:key] = setting(Hash(String, Int32), :key)
end
status["key"]?.should eq {"value" => 1234}
```

feat(driver-specs/runner): add support for testing define_setting

---

shard.yml
src/placeos-driver/interface/camera.cr
src/placeos-driver/transport.cr

so they can define a custom HTTP endpoint

feat(transport): provide a http_uri_override for non-http drivers
